name: test_python_poetry

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install Poetry
        uses: snok/install-poetry@v1 # Simplifies installation
        with:
          virtualenvs-in-project: true # For caching
      - name: Cache venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --with dev
      - name: Lint with Ruff
        run: poetry run ruff check
      - name: Run tests
        run: poetry run pytest
