"""create pokemon tables

Revision ID: 38e1eb4dfa35
Revises:
Create Date: 2026-03-10 00:23:43.468133

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38e1eb4dfa35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pokemon',
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('height', sa.Integer(), nullable=False),
        sa.Column('weight', sa.Integer(), nullable=False),
        sa.Column('base_experience', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('pokemon_id'),
    )
    op.create_table(
        'pokemon_ability',
        sa.Column('ability_name', sa.String(), nullable=False),
        sa.Column('is_hidden', sa.Boolean(), nullable=False),
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['pokemon_id'],
            ['pokemon.pokemon_id'],
            onupdate='cascade',
            ondelete='cascade',
        ),
        sa.PrimaryKeyConstraint('ability_name', 'pokemon_id'),
    )
    op.create_table(
        'pokemon_stats',
        sa.Column('stat_name', sa.String(), nullable=False),
        sa.Column('base_stat', sa.Integer(), nullable=False),
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['pokemon_id'],
            ['pokemon.pokemon_id'],
            onupdate='cascade',
            ondelete='cascade',
        ),
        sa.PrimaryKeyConstraint('stat_name', 'pokemon_id'),
    )
    op.create_table(
        'pokemon_type',
        sa.Column('type_name', sa.String(), nullable=False),
        sa.Column('pokemon_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['pokemon_id'],
            ['pokemon.pokemon_id'],
            onupdate='cascade',
            ondelete='cascade',
        ),
        sa.PrimaryKeyConstraint('type_name', 'pokemon_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_type')
    op.drop_table('pokemon_stats')
    op.drop_table('pokemon_ability')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
