class OperadorArmazenamento:
    def init(self): ...

    def registra_dados_brutos():
        try:
            ...
        except:
            ...

    def registra_dados_bd():
        try:
            ...
        except:
            ...
